/*
 * MenuConstants.h
 *
 *  Created on: Dec 17, 2013
 *      Author: pschmitt
 */

#ifndef MENUCONSTANTS_H_
#define MENUCONSTANTS_H_

// Menu strings
#define MENU_WIND_STR "Wind Strength"
#define MENU_WIND_NONE "None"
#define MENU_WIND_WEAK "Weak"
#define MENU_WIND_NORMAL "Normal"
#define MENU_WIND_STRONG "Strong"
#define MENU_WIND_DIR "Wind direction"
#define MENU_WIND_NORTH "North"
#define MENU_WIND_SOUTH "South"
#define MENU_WIND_EAST "East"
#define MENU_WIND_WEST "West"
#define MENU_WIND_NORTH_EAST "North-East"
#define MENU_WIND_NORTH_WEST "North-West"
#define MENU_WIND_SOUTH_EAST "South-East"
#define MENU_WIND_SOUTH_WEST "South-West"
#define MENU_COLOR "Color"
#define MENU_COLOR_RED "Red"
#define MENU_COLOR_GREEN "Green"
#define MENU_COLOR_BLUE "Blue"
#define MENU_COLOR_YELLOW "Yellow"
#define MENU_COLOR_WHITE "White"
#define MENU_COLOR_BLACK "Black"
#define MENU_AUTO_PILOT "Auto pilot"
#define MENU_LIGHT "Lights"
#define MENU_LIGTH1_ENABLE "Enable Light 1"
#define MENU_LIGTH1_DISABLE "Disable Light 1"
#define MENU_LIGTH2_ENABLE "Enable Light 2"
#define MENU_LIGTH2_DISABLE "Disable Light 2"

#define MENU_QUIT "Quit"

enum {
	MENU_QUIT_ID = 0,
	MENU_WIND_ID,
	MENU_WIND_NONE_ID,
	MENU_WIND_WEAK_ID,
	MENU_WIND_NORMAL_ID,
	MENU_WIND_STRONG_ID,
	MENU_WIND_NORTH_ID,
	MENU_WIND_SOUTH_ID,
	MENU_WIND_WEST_ID,
	MENU_WIND_EAST_ID,
	MENU_WIND_NORTH_EAST_ID,
	MENU_WIND_NORTH_WEST_ID,
	MENU_WIND_SOUTH_WEST_ID,
	MENU_WIND_SOUTH_EAST_ID,
	MENU_COLOR_RED_ID,
	MENU_COLOR_BLUE_ID,
	MENU_COLOR_GREEN_ID,
	MENU_COLOR_YELLOW_ID,
	MENU_COLOR_WHITE_ID,
	MENU_COLOR_BLACK_ID,
	MENU_LIGTH1_ENABLE_ID,
	MENU_LIGTH1_DISABLE_ID,
	MENU_LIGTH2_ENABLE_ID,
	MENU_LIGTH2_DISABLE_ID,
	MENU_AUTO_PILOT_ID
};

#endif /* MENUCONSTANTS_H_ */
